# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4qbYQ9xpwEJFN3xn3B_DgJdeLGUvsTw
"""

import time
while True:
  print("Dashing through the snowwWwWWwWwww")
  time.sleep(1.75)
  print("In a rusty ChevroleeEEeEet")
  time.sleep(1.75)
  print("Down the road I goooOoOOoo")
  time.sleep(1.75)
  print("Sliding all the waaaaay")
  time.sleep(1.75)
  print("I need new piston rings")
  time.sleep(1.75)
  print("I need some new snow tires")
  time.sleep(1.75)
  print("My car is held to-gether by a piece of chicken wire")
  time.sleep(2.5)
  print("Oh")
  time.sleep(0.5)
  print("Rust n Smoke")
  time.sleep(1)
  print("The heater broke")
  time.sleep(1)
  print("The door just blew away")
  time.sleep(2)
  print("I light a match")
  time.sleep(1)
  print("To see the dash")
  time.sleep(1)
  print("And then I start to pray-AY")
  time.sleep(2)
  print("The frame is bent")
  time.sleep(1)
  print("The muffler went")
  time.sleep(1)
  print("The radio it's ok")
  time.sleep(2)
  print("Oh what fun it is to ride this rusty cheverolet")
  time.sleep(5)